pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: CopyFiles@2
  inputs:
    contents: arm/dtcli-webproxy-container/*.json
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: ArmJsonTemplates
